### PR TITLE
add makefile and script to build xml file

### PR DESCRIPTION
**Pull request by Ste74**
@oberon2007 if you like you have only to modify the cinnamon wallpapers pkg in the pkgbuild .. i have created the folder wich contain your artowork for cinnamon via makefile :stuck_out_tongue_winking_eye: 

EDIT: the script work also with png and any other files supported by Gnome ( or mate ) we have only to re add the function to enumerate other files
Signed-off-by: Ste74 <stefano@manjaro.org>

### CODE REVIEW

**Comment by Ste74** [comment]
@oberon2007 
https://github.com/oberon2007/artwork-manjaro-cinnamon/pull/1/commits/9af0e11da9b2ba84d820dbfb4d52e054db47556a#diff-009be87809764c481dbf33bc85b0a462R5
https://github.com/manjaro/manjaro-wallpapers-18.0/commit/46e4c86b3fe04d489642aca1631f56ebc71e6a5a#diff-6b22d3d95dcf8ce08362f15a798ae7a6R5
is this what you mean ?

**Comment by oberon-manjaro** [comment]
Looking great my friend. Thanks a bunch!
Let's just build a pkg and see how it performs :smiley:

**Comment by oberon-manjaro** [comment]
I will update my PKGBUILD...

**Comment by Ste74** [comment]
:smile: my pleasure .. Is ok also rename manjaro-wallpapers-18.0 to Illyaria ?

**Comment by oberon-manjaro** [comment]
The package you mean? I think **manjaro-wallpapers-18.0** is ok, since it will be the logical successor of the 17.0 package. But the theme name for the preview I think will be good if it is listed as **Illyria**. What do you think?

**Comment by Ste74** [comment]
Ahh you mean **Illyria** for the xml name and **manjaro-wallpapers-18.0** for the folder in **/usr/share/backgrounds** ?

**Comment by oberon-manjaro** [comment]
No, I meant **manjaro-wallpapers-18.0** just for pkgname and folder plus xml name **Illyria** :smiley: , good?

**Comment by oberon-manjaro** [comment]
Well the xml name is automatically the name of the folder, isn't it?

**Comment by oberon-manjaro** [comment]
Looks like a huge success! Awesome, thank you maestro!

screenshot_2018-05-21_23-59-20

**Comment by oberon-manjaro** [comment]
Ah, right. The name of the xml file is what's being used for the listing... Like this I think would be nice:

screenshot_2018-05-22_00-51-44

**Pull request merged**
